#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.BiosBootSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.IntegratedDevices
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.MemSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.MiscSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.OneTimeBoot
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.ProcSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.SataSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.SerialCommSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.SlotDisablement
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.SysInformation
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.SysProfileSettings
#/opt/dell/srvadmin/bin/idracadm7 -r 100.71.102.8 -u root -p calvin --nocertwarn get Bios.SysSecurity
